title: Emre Altintas
description: Datamatikerstudernde
site_title: 'Emre Altintas'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: emrealtiintas
email: emrealtintas@live.dk

# absolute or relative
profile_picture: assets/images/emre.jpg

# Google Analytics ID
google_analytics: 
